// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoamJqvMdNdVqLRBYGmVzcHUEdwMw_MJY',
    appId: '1:448233567790:web:7d6864e21ec504ed6ed1bf',
    messagingSenderId: '448233567790',
    projectId: 'project-medusa-48434',
    authDomain: 'project-medusa-48434.firebaseapp.com',
    storageBucket: 'project-medusa-48434.appspot.com',
    measurementId: 'G-4GEB0LZ3XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBB4N9of2RFV7rgK2euu5lBSyYnfZUX18',
    appId: '1:448233567790:android:bf80c51c15936f726ed1bf',
    messagingSenderId: '448233567790',
    projectId: 'project-medusa-48434',
    storageBucket: 'project-medusa-48434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqNOwRF7swAD1s2r0NDHzV6gk2-GkRTU',
    appId: '1:448233567790:ios:d3adfca5e29590106ed1bf',
    messagingSenderId: '448233567790',
    projectId: 'project-medusa-48434',
    storageBucket: 'project-medusa-48434.appspot.com',
    iosClientId: '448233567790-2pdik5he5g1mpsal6qbia9skdeqc89dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMedusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdqNOwRF7swAD1s2r0NDHzV6gk2-GkRTU',
    appId: '1:448233567790:ios:d3adfca5e29590106ed1bf',
    messagingSenderId: '448233567790',
    projectId: 'project-medusa-48434',
    storageBucket: 'project-medusa-48434.appspot.com',
    iosClientId: '448233567790-2pdik5he5g1mpsal6qbia9skdeqc89dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMedusa',
  );
}
